[versions]

buildToolsVersion = "33.0.1"
minSdk = "21"
compileSdk = "33"

kotlin = "1.8.0"
appCompat = "1.5.1"
coreKtx = "1.9.0"

junit = "4.13.2"
extJunit = "1.1.4"
runner = "1.5.1"
espressoCore = "3.5.0"
mockito = "4.9.0"

androidGradle = "7.3.1"
publish = "0.22.0"
dokka = "1.7.20"

browser = "1.4.0"
robolectric = "4.9.2"

[libraries]
# AndroidX
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }

junit = { module = "junit:junit", version.ref = "junit" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
extJunit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
mockito = { module = "org.mockito:mockito-android", version.ref = "mockito" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
# Android
android-library = { id = "com.android.library", version.ref = "androidGradle" }
android-gradle = { id = "com.android.tools.build:gradle", version.ref = "androidGradle" }

# Kotlin
kotlin-gradle = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

# Other
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }